// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: protobuf/msg.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg_ChatType int32

const (
	Msg_SINGLE Msg_ChatType = 0
	Msg_GROUP  Msg_ChatType = 1
)

// Enum value maps for Msg_ChatType.
var (
	Msg_ChatType_name = map[int32]string{
		0: "SINGLE",
		1: "GROUP",
	}
	Msg_ChatType_value = map[string]int32{
		"SINGLE": 0,
		"GROUP":  1,
	}
)

func (x Msg_ChatType) Enum() *Msg_ChatType {
	p := new(Msg_ChatType)
	*p = x
	return p
}

func (x Msg_ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg_ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_msg_proto_enumTypes[0].Descriptor()
}

func (Msg_ChatType) Type() protoreflect.EnumType {
	return &file_protobuf_msg_proto_enumTypes[0]
}

func (x Msg_ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg_ChatType.Descriptor instead.
func (Msg_ChatType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_msg_proto_rawDescGZIP(), []int{0, 0}
}

type Msg_MsgType int32

const (
	Msg_TEXT   Msg_MsgType = 0
	Msg_IMAGE  Msg_MsgType = 1
	Msg_VOICE  Msg_MsgType = 2
	Msg_VIDEO  Msg_MsgType = 3
	Msg_EVENT  Msg_MsgType = 4
	Msg_NOTIFY Msg_MsgType = 5
)

// Enum value maps for Msg_MsgType.
var (
	Msg_MsgType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "VOICE",
		3: "VIDEO",
		4: "EVENT",
		5: "NOTIFY",
	}
	Msg_MsgType_value = map[string]int32{
		"TEXT":   0,
		"IMAGE":  1,
		"VOICE":  2,
		"VIDEO":  3,
		"EVENT":  4,
		"NOTIFY": 5,
	}
)

func (x Msg_MsgType) Enum() *Msg_MsgType {
	p := new(Msg_MsgType)
	*p = x
	return p
}

func (x Msg_MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg_MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_msg_proto_enumTypes[1].Descriptor()
}

func (Msg_MsgType) Type() protoreflect.EnumType {
	return &file_protobuf_msg_proto_enumTypes[1]
}

func (x Msg_MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg_MsgType.Descriptor instead.
func (Msg_MsgType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_msg_proto_rawDescGZIP(), []int{0, 1}
}

// 未发送，已发送，已送达，已读取
type Msg_MsgStatus int32

const (
	Msg_FAIL    Msg_MsgStatus = 0
	Msg_SENT    Msg_MsgStatus = 1
	Msg_ARRIVED Msg_MsgStatus = 2
	Msg_READ    Msg_MsgStatus = 3
)

// Enum value maps for Msg_MsgStatus.
var (
	Msg_MsgStatus_name = map[int32]string{
		0: "FAIL",
		1: "SENT",
		2: "ARRIVED",
		3: "READ",
	}
	Msg_MsgStatus_value = map[string]int32{
		"FAIL":    0,
		"SENT":    1,
		"ARRIVED": 2,
		"READ":    3,
	}
)

func (x Msg_MsgStatus) Enum() *Msg_MsgStatus {
	p := new(Msg_MsgStatus)
	*p = x
	return p
}

func (x Msg_MsgStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg_MsgStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_msg_proto_enumTypes[2].Descriptor()
}

func (Msg_MsgStatus) Type() protoreflect.EnumType {
	return &file_protobuf_msg_proto_enumTypes[2]
}

func (x Msg_MsgStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg_MsgStatus.Descriptor instead.
func (Msg_MsgStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_msg_proto_rawDescGZIP(), []int{0, 2}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq         uint32        `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	FromUserId  string        `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId    string        `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ChatType    Msg_ChatType  `protobuf:"varint,5,opt,name=chat_type,json=chatType,proto3,enum=model.Msg_ChatType" json:"chat_type,omitempty"`
	MsgType     Msg_MsgType   `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3,enum=model.Msg_MsgType" json:"msg_type,omitempty"`
	Status      Msg_MsgStatus `protobuf:"varint,7,opt,name=status,proto3,enum=model.Msg_MsgStatus" json:"status,omitempty"`
	Content     string        `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	AccessToken string        `protobuf:"bytes,9,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_protobuf_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Msg) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Msg) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Msg) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Msg) GetChatType() Msg_ChatType {
	if x != nil {
		return x.ChatType
	}
	return Msg_SINGLE
}

func (x *Msg) GetMsgType() Msg_MsgType {
	if x != nil {
		return x.MsgType
	}
	return Msg_TEXT
}

func (x *Msg) GetStatus() Msg_MsgStatus {
	if x != nil {
		return x.Status
	}
	return Msg_FAIL
}

func (x *Msg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Msg) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_protobuf_msg_proto protoreflect.FileDescriptor

var file_protobuf_msg_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xdb, 0x03, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63,
	0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4d,
	0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x21, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x10, 0x01, 0x22, 0x4b, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10,
	0x05, 0x22, 0x36, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x54,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x52, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_msg_proto_rawDescOnce sync.Once
	file_protobuf_msg_proto_rawDescData = file_protobuf_msg_proto_rawDesc
)

func file_protobuf_msg_proto_rawDescGZIP() []byte {
	file_protobuf_msg_proto_rawDescOnce.Do(func() {
		file_protobuf_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_msg_proto_rawDescData)
	})
	return file_protobuf_msg_proto_rawDescData
}

var file_protobuf_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protobuf_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_msg_proto_goTypes = []interface{}{
	(Msg_ChatType)(0),  // 0: model.Msg.ChatType
	(Msg_MsgType)(0),   // 1: model.Msg.MsgType
	(Msg_MsgStatus)(0), // 2: model.Msg.MsgStatus
	(*Msg)(nil),        // 3: model.Msg
}
var file_protobuf_msg_proto_depIdxs = []int32{
	0, // 0: model.Msg.chat_type:type_name -> model.Msg.ChatType
	1, // 1: model.Msg.msg_type:type_name -> model.Msg.MsgType
	2, // 2: model.Msg.status:type_name -> model.Msg.MsgStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_msg_proto_init() }
func file_protobuf_msg_proto_init() {
	if File_protobuf_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_msg_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_msg_proto_goTypes,
		DependencyIndexes: file_protobuf_msg_proto_depIdxs,
		EnumInfos:         file_protobuf_msg_proto_enumTypes,
		MessageInfos:      file_protobuf_msg_proto_msgTypes,
	}.Build()
	File_protobuf_msg_proto = out.File
	file_protobuf_msg_proto_rawDesc = nil
	file_protobuf_msg_proto_goTypes = nil
	file_protobuf_msg_proto_depIdxs = nil
}
